config/routes.rb
# Defines the routes for the application
Rails.application.routes.draw do
  root "articles#index" # Defines the root path route ("/")

  #get "/articles", to: "articles#index" # Defines the articles path route ("/articles")
  #get "/articles/:id", to: "articles#show" # Defines the article path route ("/articles/:id") eg. /articles/1

  resources :articles do # Defines the articles path route ("/articles")
    resources :comments # Defines the comments path route ("/articles/:article_id/comments")
  end
end

# Path: app/controllers/articles_controller.rb

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible # include the Visible module from app/models/concerns/visible.rb
    #has_many is a Rails method that indicates an Article can have many Comments. 
    #The dependent: :destroy option tells Rails to delete all the comments associated with the article if the article itself is ever destroyed:
    has_many :comments, dependent: :destroy 
   
    validates :title, presence: true # validates that the title attribute is present
    validates :body, presence: true, length: { minimum: 10 } # validates that the body attribute is present and has a minimum length of 10 characters


    
    
   

end
  

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible # include the Visible module from app/models/concerns/visible.rb
  belongs_to :article # a comment belongs to an article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    def archived?
      status == 'archived'
    end

    #Class methods can also be added to concerns. If we want to display a count of public articles or comments on our main page, we might add a class method to Visible as follows:
    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #http basic authentication.
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  # Defines the @articles instance variable
  def index
    @articles = Article.all 
  end

  # Defines the @article instance variable.
  def show
    @article = Article.find(params[:id]) 
  end

  # the new action instantiates a new article object, but does not save it.
  # Defines the @article instance variable.
  def new
    @article = Article.new 
  end

  #the create action instantiates a new article object and saves attempts to save it.
  def create
    # Defines the @article instance variable, article_params is a private method.
    @article = Article.new(article_params) 
    # If the article is saved successfully, redirect to the article's path.
    if @article.save # model validation. if it passes, it will save the article to the database.
      redirect_to @article
    # Otherwise, render the new template with an unprocessable entity status, which is a 422 error.
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article= Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article= Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other # 303 status code
  end

  #
  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
    
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article) # redirect to the article show page
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
      end


    private
        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form|%>
<div>
    <%= form.label :title%><br> <!-- the br tag is used to create a line break -->
    <%= form.text_field :title%>
    <%= article.errors.full_messages_for(:title).each do|message|%>
    <div><%= message%></div>
    <%end%>
</div>

<div>
    <%= form.label :body%><br>
    <%= form.text_area :body%>
    <%= article.errors.full_messages_for(:body).each do|message|%>
    <div><%= message%></div>
    <%end%>
</div>

<div>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
</div>

<div>
    <%= form.submit%>
</div>
<%end%>

<!-- the only difference between _from and new is that article is existed and @article is the object-->

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<p>Our blog has <%= Article.public_count %> articles</p>
<!-- 
<% %> 标记用于执行 Ruby 代码，但不会将结果输出到视图(View)中。这种标记通常用于控制流语句，如 if、unless、while、for 等。
<%= %> 标记用于执行 Ruby 代码，并将结果输出到视图中。这种标记通常用于输出变量、方法调用或表达式的结果。
-->

<ul>
    <% @articles.each do |article|%>
        <% unless article.archived? %>
            <li>
            <!-- 下面是使用Rails的link_to方法创建的链接-->
                <%= link_to article.title, article %>
            <!-- The link_to helper renders a link with its first argument as the link's text and its second argument as the link's destination -->
            </li>
        <% end %>
    <% end %>
</ul>

<%= link_to "New Article", new_article_path%>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<!--edit_article_path is a helper method, which returns the path of the article, eg /articles/1/edit.-->

<ul>
  <li><%= link_to "Back", articles_path %></li>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %> <!-- render @article.comments is equivalent to render partial: "comments/comment", collection: @article.comments -->

<h2>Add a Comment</h2>
<%= render "comments/form" %> 
<!-- we want to render _form.html.erb in app/views/comments-->

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<div>

<p>
  <strong><%= comment.commenter %></strong>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

 <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>

</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
 <div>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
 </div>
 
 <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
 </div>

 <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
 <div>
 
 </div>
    <%= form.submit %>
 </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>